# Generated by Django 3.1.2 on 2020-11-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='continent',
            field=models.CharField(default='North America', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='project',
            name='pledges',
            field=models.IntegerField(default=0),
        ),
    ]
